# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategy',
            options={'verbose_name_plural': 'Strategies'},
        ),
        migrations.RenameField(
            model_name='ticker',
            old_name='name',
            new_name='symbol',
        ),
    ]
