# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 13:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='backtests',
            name='strategy_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processor.Strategy'),
        ),
        migrations.AddField(
            model_name='backtests',
            name='ticker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processor.Ticker'),
        ),
        migrations.AddField(
            model_name='backtests',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
