# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='decoded_strategy',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
