# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0002_strategy_decoded_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='profit_booking',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='stop_loss',
            field=models.FloatField(null=True),
        ),
    ]
