# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0002_auto_20170323_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='ticker',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='processor.Ticker'),
        ),
    ]
