# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0003_auto_20170427_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backtests',
            old_name='shares',
            new_name='trade_quantity',
        ),
        migrations.AlterField(
            model_name='backtests',
            name='buid',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
