# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0004_auto_20170323_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='name',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
