# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0004_auto_20170510_0121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backtests',
            old_name='strategy_id',
            new_name='strategy',
        ),
    ]
