# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0005_auto_20170511_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategy',
            old_name='strategy',
            new_name='buy_strategy',
        ),
        migrations.RenameField(
            model_name='strategy',
            old_name='decoded_strategy',
            new_name='decoded_buy_strategy',
        ),
        migrations.AddField(
            model_name='strategy',
            name='decoded_sell_strategy',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='sell_strategy',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
