# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0006_auto_20170323_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='name',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
