# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0008_auto_20170323_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(blank=True, max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Indicators',
            },
        ),
    ]
