# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0009_indicators'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='uin',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
