# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0010_ticker_uin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicators',
            name='name',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
