# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0011_auto_20170326_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='shares',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
