# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 13:04
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processor', '0012_strategy_shares'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backtests',
            fields=[
                ('buid', models.CharField(max_length=32, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Only alphanumeric characters are allowed', regex='^[0-9a-z]*$')])),
                ('pnl', models.FloatField(null=True)),
                ('volatility', models.FloatField(null=True)),
                ('sharpe_ratio', models.FloatField(null=True)),
                ('sortino_ratio', models.FloatField(null=True)),
                ('max_drawdown', models.FloatField(null=True)),
                ('winning_rate', models.FloatField(null=True)),
                ('losing_rate', models.FloatField(null=True)),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Backtests',
            },
        ),
        migrations.AddField(
            model_name='strategy',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
