# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0013_auto_20170326_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtests',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='backtests',
            name='shares',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtests',
            name='strategy_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processor.Strategy'),
        ),
        migrations.AddField(
            model_name='backtests',
            name='ticker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processor.Ticker'),
        ),
        migrations.AddField(
            model_name='backtests',
            name='trade_frequency',
            field=models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('minute', 'minute'), ('hourly', 'hourly'), ('monthly', 'monthly')], default='daily', max_length=10),
        ),
        migrations.AddField(
            model_name='strategy',
            name='trade_frequency',
            field=models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('minute', 'minute'), ('hourly', 'hourly'), ('monthly', 'monthly')], default='daily', max_length=10),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
