# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchSid',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('exchange', models.CharField(choices=[('nse', 'nse')], default='nse', max_length=6)),
                ('uin', models.CharField(blank=True, max_length=20, unique=True)),
            ],
        ),
    ]
