# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fetchsid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FetchSid',
        ),
    ]
